run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - revive
    - misspell
    - prealloc

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - hugeParam
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: exported
        disabled: true
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
        disabled: true
  misspell:
    locale: US

issues:
  max-issues-per-linter: 50
  max-same-issues: 5
